### ISSUE TITLE
 Templating init failed Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by counter2015** [starsliao/Prometheus#10]
我已阅读`README.md`
当前的问题：

![7](https://user-images.githubusercontent.com/13608862/56489019-e4907580-6512-11e9-9333-a0db09ace639.png)

## 系统环境
|模块名称|版本号|
| ---         | -----   |
|grafana |6.1.3|
|prometheus |2.9.1.linux-amd64|
|node_exporter| 0.17.0|

## 系统配置
|项目|配置|
|-----|-----|
|hosts|mycentos|
|ip|192.168.22.129|
|操作系统|centos 7|

![41](https://user-images.githubusercontent.com/13608862/56488898-764bb300-6512-11e9-922e-a38cd927903a.png)

## Prometheus 配置文件
```yml
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.22.129:9090']
      labels:
        instance: prometheus

  - job_name: "job1"
    static_configs:
    - targets: ['192.168.22.129:9100']
      labels:
        instance: instance1
```

## DataSource配置
![903](https://user-images.githubusercontent.com/13608862/56489657-fd018f80-6514-11e9-8302-8f82be5206bc.png)

之前尝试过的步骤
- 安装饼状插图
- 手动修改主机名为`mycentos`,节点名为`192.168.22.129:9100`
- 修改grafana版本为5.2.4

上面的步骤并没有对结果产生影响。

在Prometheus中查询各node的instance格式和版本如下
![2831](https://user-images.githubusercontent.com/13608862/56489185-75675100-6513-11e9-8629-daf0c6d045d0.png)

> 必须：$node取值node_exporter的instance，IP+端口格式。该看板大部分查询关联了这个变量，请确保该变量有效：

这一段中的`$node`是手动配置还是自动配置的？形如"instance1,192.168.22.129:9100"这样设置吗？

我一周前开始接触Prometheus和Grafana，现在想跑一个示例来监控机器的基本运行情况，但是目前的情况看起来像是某些变量配置错误，或者Grafana没有正确读取对应的节点信息，所以导致图表数据没有正常返回。

仪表盘的变量如下
![14](https://user-images.githubusercontent.com/13608862/56489814-929d1f00-6515-11e9-89fc-5e328875ed58.png)

我是不是需要手动修改`name`和`node`的值？
我该怎么做才能让图表正常显示呢？

以CPU使用率为例，在Grafana中不能正确显示
![4840](https://user-images.githubusercontent.com/13608862/56489999-3e466f00-6516-11e9-880f-627e6044ce13.png)

但是在Prometheus中可以查询到正确结果
![821](https://user-images.githubusercontent.com/13608862/56490035-5cac6a80-6516-11e9-80e8-d62c1f85fd00.png)
