### ISSUE TITLE
数据展示重复

### ISSUE THREAD

**Issue by PatHoo** [starsliao/Prometheus#71]
Prometheus配置：
```
  - job_name: 'ALL'
    file_sd_configs:
      - files:
        - conf.d/*.yml
        refresh_interval: 5m

  - job_name: 'GPU'
    file_sd_configs:
      - files:
        - conf.d/gpu.yml
        refresh_interval: 5m
```
这样配置的话，Grafana中JOB可以下拉选择ALL或者GPU，但资源明细那里会重复，如下图，不知道是否Prometheus配置问题。我单机配置是48核CPU，1TB内存。
![image](https://user-images.githubusercontent.com/19948780/99158720-f5b26000-2710-11eb-9603-ddbee6446aa4.png)
