### ISSUE TITLE
blackbox_export配置

### ISSUE THREAD

**Issue by elysiumHL** [starsliao/Prometheus#9]
可否提供blackbox_export和prometheus的相关配置进行参考，谢谢

**Comment by WhellCoder** [comment]
同求blackbox_export和prometheus的相关配置

**Comment by starsliao** [comment]
prometheus方面没做什么特殊配置 ，自动发现方面是使用的consul_sd_configs
可以参考下：
```
  - job_name: 'NODE-MONITOR'
    consul_sd_configs:
      - server: '192.168.200.60:8500'
        token: 'xxxxxxxxxx'
        services: ['N-BASE','N-DEV','N-SIT','N-UAT','N-PROD']
    relabel_configs:
      - source_labels:  ["__meta_consul_tags"]
        regex: '^,(.*),(.*),(.*),(.*),$'
        target_label: 'exporter'
        replacement: $1
      - source_labels:  ["__meta_consul_service"]
        target_label: "env"
      - source_labels:  ["__meta_consul_service_id"]
        target_label: "name"
      - source_labels:  ["__meta_consul_service_address"]
        target_label: "ip"
```
blackbox.yml就是使用的默认的http和tcp监控的配置了。
